# Variables and Gradients

## Variables
     -  Wrapper around Tensor
     -  Allows accumulation of gradients

In [47]:
import torch
from torch.autograd import Variable

In [48]:
a=Variable(torch.ones(2,2),requires_grad=True)
a

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [49]:
torch.ones(2,2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [50]:
b=Variable(torch.ones(2,2),requires_grad=True)
print(a+b)
print(torch.add(a,b))

tensor([[ 2.,  2.],
        [ 2.,  2.]])
tensor([[ 2.,  2.],
        [ 2.,  2.]])


In [51]:
print(a*b)
print(torch.mul(a,b))

tensor([[ 1.,  1.],
        [ 1.,  1.]])
tensor([[ 1.,  1.],
        [ 1.,  1.]])


## Gradients
**requires_grad**
* Allows calculation of gradients w.r.t the variables

$$ y_{i}=5(x_{i}+1)^{2} $$

In [86]:
x=Variable(torch.ones(2),requires_grad=True)
print(x)
print(x.grad)

tensor([ 1.,  1.])
None


$$ y_{i}\big\rvert_{x_{i}=1} = 5(1+1)^{2}=5(2)^{2}=5(4)=20$$

In [87]:
y = 5 * (x+1) ** 2
y

tensor([ 20.,  20.])

**Backward should be called only on a scalar (i.e. 1-element tensor) or with gradient w.r.t variable)
* Thus reducing y to scalar then

$$o=\frac{1}{2}\sum_{i}y_{i}$$

In [88]:
o=(1/2)*torch.sum(y)
o

tensor(20.)

**Recap y equation:**$$ y_{i}=5(x_{i}+1)^{2} $$
**Recap o equation:** $$o=\frac{1}{2}\sum_{i}y_{i}$$
**Substitute y into o equation:** $$o=\frac{1}{2}\sum_{i}5(x_{i}+1)^{2}$$

$$\frac{\partial{o}}{\partial{x_{i}}}=\frac{1}{2}[10(x_{i}+1)]$$

$$\frac{\partial{o}}{\partial{x_{i}}}\bigg\rvert_{x_{i}=1}=\frac{1}{2}[10(1+1)]=10 $$

In [89]:
o.backward(retain_graph=True)
#Calculates the gradients given x=1
#Need to retain graph to run Backward the second time.

In [90]:
x.grad #Gradient With Respect to 10

tensor([ 10.,  10.])

In [91]:
o.backward(torch.FloatTensor([1.0,1.0]),retain_graph=True) #Putting x1=1 and x2=1
print(x.grad) #Each time you run backwards, it calculates gradients

tensor([ 20.,  20.])
